import {
  BAD_REQUEST,
  CREATED_SUCCESS,
  INTERNAL_SERVER_ERROR,
  NOT_FOUND,
  OK,
  UNAUTHORIZED,
} from "./statusCodes";
import { API_ENDPOINT } from "./api";
import {
  CONTACT_ROUTE,
  EDIT_TICKET_ROUTE,
  HOME_ROUTE,
  LOGIN_ROUTE,
  PRIORIRY_ROUTE,
  SETTINGS_ROUTE,
  SETTING_ROUTE,
  STATUS_ROUTE,
  TICKET_ROUTE,
  USERS_ROUTE,
  ME_ROUTE,
} from "./routes";

export {
  BAD_REQUEST,
  CREATED_SUCCESS,
  INTERNAL_SERVER_ERROR,
  NOT_FOUND,
  OK,
  UNAUTHORIZED,
  API_ENDPOINT,
  CONTACT_ROUTE,
  EDIT_TICKET_ROUTE,
  HOME_ROUTE,
  LOGIN_ROUTE,
  PRIORIRY_ROUTE,
  SETTINGS_ROUTE,
  SETTING_ROUTE,
  STATUS_ROUTE,
  TICKET_ROUTE,
  USERS_ROUTE,
  ME_ROUTE,
};
